### DISCUSSION TITLE
[mqtt] How to override source address of write messages?

### DISCUSSION THREAD

**Discussion by lildadou** [john30/ebusd#1246] [Q&A]
I'm trying to simulate an outdoor sensor connected via eBus to my Wolf heating system. I noticed that my heating controller was broadcasting 07h 00h telegrams (Date/Time Message of an eBUS Master) containing the time and outdoor temperature (I set a fixed resistor to make it think it was connected to a sensor). I then removed the resistor and tried to do the same thing; with no result. Unfortunately, I bought the famous outdoor sensor to find out what to do, and surprise... it too emits 07h 00h telegrams. Of course, these are taken into account by the heating system.

The only difference between my forged telegrams and hers is the source address. To confirm the hypothesis that it was this source address that was making my telegrams ineffective, I used the "override source addresse" option in ebusctl and found that it worked!
Now I'd like to achieve the same result, but from MQTT.

Wouldn't there be, for example, an option to put in the definition message so that the source address defined there is the one used by default?

PS: I forgot. Changing the address of the ebus adapter is not a solution ^^'.
Indeed, after simulating this sensor, I intend to simulate 5 heating controllers to be able to control the heating of individual rooms.

**Comment by wrongisthenewright** [comment]
Maybe you can start 5 instances of ebusd with different addresses  and add the only write parameters you need

**Reply by lildadou** [reply]
I don't think this is feasible for 2 reasons:
 - I use ebusd via Home Assistant and it doesn't seem to be able to launch several instances.
 - the adapter seems extremely low-level (no message queue, for example, but that's just a feeling) and I think it's going to cause problems.

**Reply by wrongisthenewright** [reply]
It's not feasible in your case. I don't use hassio but standard docker image in a Linux platform. The adapter I use accept multiple connections. It depends on what device you're usuing. In my case It's a matter of configuration.
Having said that I concur that it's stretching a little the purpose of ebusd. As far as I know it can't be done with standard config.

**Reply by lildadou** [reply]
It's good to know that several instances of ebusd can use the same adapter.

**Reply by lildadou** [reply]
> It's not feasible in your case. I don't use hassio but standard docker image in a Linux platform. The adapter I use accept multiple connections. It depends on what device you're usuing. In my case It's a matter of configuration. Having said that I concur that it's stretching a little the purpose of ebusd. As far as I know it can't be done with standard config.

The eBUS Adapter Shield v5 does not support multiple daemons.

**Comment by lildadou** [comment]
I found a solution with Home Assistant to broadcast 07h 00h telegrams with the desired address.

1. I create a script in the HA configuration folder:
```bash
#!/bin/bash
ebusd_container_id=2ad9b828-ebusd
echo w -V -s 0f -c broadcast datetime "$1;$2;$3" | nc ${ebusd_container_id}.local.hass.io 8888
```
2. I add a _shell command_ integration in `configuration.yaml`:
```yaml
shell_command:
  ebus_update_masterclock: >-
    ./ebus_update_masterclock {{ states('sensor.outdoor_temperature') }} {{ now().strftime('%H:%M:%S') }} {{ now().strftime('%d.%m.%Y') }}
```
3. Then I add an automation to call the command:
```yaml
alias: Heating - Datetime/Temp
description: ""
triggers:
  - seconds: /10
    trigger: time_pattern
conditions: []
actions:
  - action: shell_command.ebus_update_masterclock
    metadata: {}
    data: {}
mode: single
```
