### DISCUSSION TITLE
How to get ebusd active in home assistant

### DISCUSSION THREAD

**Discussion by jjtoard** [john30/ebusd#1303] [Q&A]
Hi I just activated the board and tried to link it to home assistant but without succes

I use the [eBUS Adapter Shield v5](https://adapter.ebusd.eu/)

I linked the board on the ebus of the vaillant.
I changed the ebus config to rx/.tx pins.  Is this OK ?
At least it states now ebusd connected but inactive
Should I do something with the delay / bitrate parameters ?

I have the feeling the ebusd doesn't see data on the bus.
Activated MQTT on ebusd but only get data for running/uptime/temp.rssi/signal but nothing else

How do I get the info active in home assistant ?

**Ok found it !!!!!!**

Ebus config on the board set back to the default value TCP so not tx/rx
In home assistant created the direcotry /config/ebusd and put there the file mqtt-hassio.cfg 
Changed in the add-on 
* the MQTT value to /config/ebusd/mqtt-hassio.cfg
*  opened the unused optional configurations
     * changed the network adapter address to 
          *  ens:<ip board>:9999

After all this 
* I could start the add-on
* I could see all the values being send via MQTT

So now looking to get all the values represented in Home Assistant.
I tought Home Assistant would recognize it as a new device but that doesn't look to be the case

**Comment by thomaskilian** [comment]
I used MQTTExplorer on my Mac to see what comes. I then found the messages under Entities (and via Devices/MQTT) in HA. Also the MQTTExplorer helped me to identify messages and to write an automation like
```
trigger:
  - platform: mqtt
    topic: ebusd/hc1/DHWTemperature
condition: []
action:
  - if:
      - condition: template
        value_template: "{{trigger.payload_json._16_Temp10.value|float(0) > 0}} "
    then:
      - service: input_number.set_value
        metadata: {}
        data:
          value: "{{(trigger.payload_json._16_Temp10.value|float)}}"
        target:
          entity_id: input_number.valid_hot_water

```

**Comment by Koky05** [comment]
Why so complicated? You could create [MQTT number](https://www.home-assistant.io/integrations/number.mqtt/) sensor:
```
# Example configuration.yaml entry
mqtt:
  - number:
      - name: valid_hot_water
         unique_id: valid_hot_water
         unit_of_measurement: "°C"
         state_topic: "ebusd/hc1/DHWTemperature"
         value_template: "{{ (value_json.[16].Temp10.value | float(0)) }}"
         command_topic: "ebusd/hc1/DHWTemperature/set"
         command_template: "{{ (value_json.[16].Temp10.value | float(0)) }}"
```
But if you use HA AutoDiscovery it should be populated in HA under MQTT integration.
