### DISCUSSION TITLE
Reduce Data and optimisation?

### DISCUSSION THREAD

**Discussion by chrissooo** [john30/ebusd#1333] [Q&A] [answered]
Hi All,

Thank you very much for that great tool! I love controlling my Vaillant gas heating with it!

First, here is my setup:
- eBUS Adapter Shield C6
- Raspberry Pi 4
- Home Assistant as Docker image (not possible to run as HA OS for another reason)
- ebusd as Docker image with the following compose file:
    ```yaml
    services:
      ebusd:
        command: -d ens:192.168.178.48:9999 --httpport=7878 --latency=10 --scanconfig --mqtthost localhost --mqttport 1883 --mqttint=/etc/ebusd/mqtt-hassio.cfg --mqttjson --mqttretain
        container_name: ebusdg
        image: john30/ebusd:latest
        network_mode: host
        restart: unless-stopped
    ```

Now the questions:

1. I run ebusd over Wi-Fi. Is it better to run it over USB? The adapter is connected over USB to the Raspberry Pi, so that should not be the problem.

2. When I run it over USB, it does not load the configs over the Internet, right?

3. When you look at the commands, I don’t pass a path to the config files. This means that these files are loaded over the Internet, right? In this case, it might be better to download them and use them locally, I think. Because what happens if there is no Internet connection?

4. I get over 600 entities in Home Assistant with this configuration. Most of them I don’t need. Maybe only 10 are in use. Would it be better to create the sensors in Home Assistant by myself? In this case, I would need to remove `mqttint=/etc/ebusd/mqtt-hassio.cfg`, right?

5. On the other hand, is it not better to modify the CSV config files and delete all sensors that are not needed and leave auto-discovery in Home Assistant? Or should I do both (reduce the CSV and remove `mqttint=/etc/ebusd/mqtt-hassio.cfg`)?

I hope the questions are understandable.
