### DISCUSSION TITLE
Fehler: unable to load scan config ed

### DISCUSSION THREAD

**Discussion by chrissooo** [john30/ebusd#1335] [Q&A]
Hi,

i get following Error. Here my compose file. The config are checkout over git and on the correct place:

```
services:
  ebusd:
    image: john30/ebusd:latest
    container_name: ebusd
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Berlin
      - EBUSD_DEVICE=ens:192.168.178.48:9999
      - EBUSD_HTTPPORT=7878
      - EBUSD_SCANCONFIG=full
      - EBUSD_CONFIGPATH=/etc/ebusd/ebusd-configuration/ebusd-2.1.x/de
      - EBUSD_CONFIGLANG=DE
      - EBUSD_LATENCY=20
      - EBUSD_MQTTHOST=localhost
      - EBUSD_MQTTPORT=1883
      - EBUSD_MQTTTOPIC=ebusd
      - EBUSD_MQTTJSON=
      - EBUSD_MQTTINT=/etc/ebusd/mqtt-hassio.cfg
      - EBUSD_MQTTRETAIN=
      - EBUSD_LOGLEVEL=error
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/data/ebusd/data:/data
      - /docker/data/ebusd/config:/etc/ebusd
      - /docker/data/ebusd/log:/var/log
```

and here the error:

```
2024-09-15 10:37:46.365 [main error] unable to load scan config ed: no file from vaillant with prefix ed matches ID "vms01", SW0116, HW0303
2024-09-15 10:37:46.366 [main error] scan config ed: ERR: element not found
```

Is it bad?
