### DISCUSSION TITLE
Set silent mode for Vaillant aroTHERM

### DISCUSSION THREAD

**Discussion by Kifo2023** [john30/ebusd#1365] [Q&A]
My Vaillant aroTHERM plus with VRC 720 SensoComfort and VR 71 Controller is running 24/7 in silent mode at 50% most  of the year to keep it quiet and to keep then number of daily starts low.

However, on very cold days I will need increase the output. I would like to control this via my home automation system.
But so far I could not get access to the silent mode percentage via ebusd. No control files seem to know this parameter.

As a work around I could also deactivate the silent mode by manipulating the silentTimer, but this seems to be not so easy, too.
I already included a sielntTimer section in my 15.ctlv2.csv file, but I could not even read the timer data. Ebusd tells "element not found".

Does anybody have experience with this topic?

**Comment by dylan09** [comment]
I have a register `CompressorSilentOperationLevel` in file `08.hmu00.csv`  (ID is FF3428). Maybe this is the right place to change. Couldn`t test it myself. Didn't find a way to change the silent.Timer configuration via eBus.

Could you test if that's the right register. And give some feedback?

**Comment by dylan09** [comment]
One question to the timer section for the sensoComfort: Could help someone in changing this timers through eBus?
I have tried to change the definition to writable. But was not able to set some new values.

**Comment by Kifo2023** [comment]
I tried to include the CompressorSilentOperationLevel parameterin my file 08.hmu.csv, but probably I did not interpret the advise about[ how to work on the configuration file](https://github.com/john30/ebusd/wiki/4.1.-Message-definition) right.

I put a new line under
"# Heat pump configuration menu values"
with the following content:
r,,CompressorSilentOperationLevel,,,,,FF3428
and tried also
r,,CompressorSilentOperationLevel,,,,,FF3428,,,UCH,,,Percent,

but both do not work. The ebusd log file sais:
2024-10-27 08:12:24.492 [update error] unable to parse read hmu CompressorSilentOperationLevel from 3108b51a0605ff32ff3428 / 02ff01: ERR: invalid position
2024-10-27 08:12:24.492 [main error] read hmu CompressorSilentOperationLevel: decode ERR: invalid position

Can you help me to put it right?

**Reply by chrizzzp** [reply]
@Kifo2023 

`08.hmu.csv`:

```
*r,,,,,,B51A,05,,,IGN:3,,,,,,,,,,,,,,,,,,,,,
*w,,,,,,B51A,06,,,,,,,,,,,,,,,,,,,,,,,,
r;w,,CompressorSilentOperationLevel,,,,,FF3428,,,percent0,,,Compressor Silent Operation level,,,,,,,,,,,,,,,,,,
```
The template `percent0`  is defined as:
`percent0,UCH,,%,`

The SilentOperationLevel can be set only in a limit range (40 - 60% on my split system).

@dylan09 

I created two scripts in Home Assistant  which activate/deactivate the 'SilentOperation' by adjusting the silent mode timers in the VRC720 via MQTT/ebusd:

to turn silent mode off:
("Flüstermodus" = silent mode)

```
mqtt_wp_flustermodus_aus:
  alias: 'MQTT: WP Flüstermodus Aus'
  sequence:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Monday/set
      payload: 0;1;00:00;00:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Tuesday/set
      payload: 0;1;00:00;00:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Wednesday/set
      payload: 0;1;00:00;00:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Thursday/set
      payload: 0;1;00:00;00:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Friday/set
      payload: 0;1;00:00;00:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Saturday/set
      payload: 0;1;00:00;00:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Sunday/set
      payload: 0;1;00:00;00:00;ff ff
  mode: single
  icon: mdi:heat-pump


```

to turn silent mode on:

```
mqtt_wp_flustermodus_an:
  alias: 'MQTT: WP Flüstermodus An'
  sequence:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Monday/set
      payload: 0;1;00:00;24:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Tuesday/set
      payload: 0;1;00:00;24:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Wednesday/set
      payload: 0;1;00:00;24:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Thursday/set
      payload: 0;1;00:00;24:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Friday/set
      payload: 0;1;00:00;24:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Saturday/set
      payload: 0;1;00:00;24:00;ff ff
  - service: mqtt.publish
    metadata: {}
    data:
      qos: '2'
      retain: false
      topic: ebusd/ctlv2/silentTimer.Sunday/set
      payload: 0;1;00:00;24:00;ff ff
  mode: single
  icon: mdi:heat-pump
```
