### DISCUSSION TITLE
Vaillant EcoTec 28 - Cannot control HC

### DISCUSSION THREAD

**Discussion by AbsurdSyssie** [john30/ebusd#1491] [Q&A]
# Issue: Unable to Send Commands to eBUS

## Description

I have set up **eBUSd** on my Vaillant **ecoTEC 28** following the documented process. The system successfully detects devices and communicates over MQTT, but **writing commands (e.g., setting TimerInputHc) does not work and returns 'unknown command' in logs**.
I load bai.308523.inc and 08.bai.csv by default and have used enabledefine to set timerinputhc to write. 

### **Expected Behavior**

- When sending a write command to modify `TimerInputHc` (e.g., `ebusctl write TimerInputHc 1` or via MQTT), the change should be reflected in the system.
- MQTT messages should update accordingly.

### **Actual Behavior**

- Writing `TimerInputHc` over MQTT results in no change to input state in eBUSd logs.
- `ebusctl find -w` returns `bai TimerInputHc = no data stored`.
- Polling `TimerInputHc` always returns `off`.

---

### **1. Firmware Installation**

1. Connected to PC via cable.
2. Installed latest firmware via [[official firmware page](https://adapter.ebusd.eu/v5-c6/firmware.en)](https://adapter.ebusd.eu/v5-c6/firmware.en).
3. Unplugged and replugged the device.

### **2. WiFi Connection**

- Configured the WiFi using the firmware webpage.
- SSID and password entered correctly.

### **3. eBUSd Docker Configuration**

Docker Compose:

```yaml
version: '3.8'
services:
  ebusd:
    image: john30/ebusd
    container_name: ebusd
    ports:
      - "3005:8888"
    command: "--scanconfig -d ens:192.168.1.175:9999 --enabledefine --accesslevel=* --latency=10 --mqtthost=mosquitto --mqttport=1883 --mqtttopic=ebusd --mqttjson --mqttint=/etc/ebusd/mqtt-hassio.cfg --mqttvar=filter-direction=r|u|^w"
    restart: unless-stopped
    networks:
      - gptarrs_default
```

**eBUSd Log Output**:

```
2025-01-23 17:31:01.581 [device notice] transport opened
2025-01-23 17:31:02.788 [bus notice] bus started with own address 31/36

address 03: master #11
address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0518;HW=7401", loaded "vaillant/bai.308523.inc" ([id_hw=7401]), "vaillant/08.bai.csv"
address 10: master #2
address 15: slave #2, scanned "MF=Vaillant;ID=05000;SW=0113;HW=9601"
```

### **4. MQTT Configuration**

- Running Mosquitto in a separate Docker container:

```yaml
version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    restart: unless-stopped
```

- Confirmed MQTT messages are being received:

```
MQTT Message on ebusd/bai/TimerInputHc:
{
     "value": {"value": "off"}}
```

---

## **Debugging Attempts**

1. **Defined ****************`TimerInputHc`**************** for Writing**:

   ```
   ebusctl define -r " r5;w,bai,TimerInputHc,Eingang Schaltuhr: timer input (block heatdemand),,08,b509,0dde00,value,s,UCH,0=off;1=on,,"
   ```

   - Successfully appears as writable in `ebusctl find -w` but reports `no data stored`.

2. **Tried Writing ****************`TimerInputHc`**************** via MQTT**:
ebusd/bai/TimerInputHc/set

   - Messages sent: `{ "value": { "value": "1" } }`\

     ```
     { 
     ```
     ```
      "value": {"value": "off"}}
     ```
     Log response:

   ```
   [mqtt notice] write bai TimerInputHc: 1
   2025-02-19 15:23:16.450 [update notice] sent poll-read bai TimerInputHc QQ=31: off
   ```

   - No actual change in value.
   - 
---

## **Questions & Help Needed**

1. **Why does ****************`TimerInputHc`**************** appear writable but cannot be modified?**
2. **How can I remotely toggle heating using ****************`TimerInputHc`****************?**
3. **Are there alternative commands to control heating via eBUS?**

Would appreciate any guidance or troubleshooting steps to resolve this issue!

---

### **References**

- [[eBUSd Wiki](https://github.com/john30/ebusd/wiki)](https://github.com/john30/ebusd/wiki)
- [[MQTT Integration](https://github.com/john30/ebusd/wiki/MQTT-integration)](https://github.com/john30/ebusd/wiki/MQTT-integration)
- [[Config Files](https://github.com/john30/ebusd-configuration/blob/master/ebusd-2.1.x/en/vaillant/bai.308523.inc)](https://github.com/john30/ebusd-configuration/blob/master/ebusd-2.1.x/en/vaillant/bai.308523.inc)

Thanks in advance for any help!
