### DISCUSSION TITLE
Help for ebusd and homeassistant via docker compose

### DISCUSSION THREAD

**Discussion by DeltaTango69** [john30/ebusd#1493] [Q&A]
Hi all,

I have installed the ebus adapter shield and get following status:

![image](https://github.com/user-attachments/assets/ee369b7d-1dfb-4e44-8445-4324ce78a19b)

so i think this is ok so far:

To get the infos to homeassistant  I have to start the mqtt service i think. The docker compose is very big and I don't reallyunterstand what I need and what not. So far there are no mqtt messages and so there is nothing to see in homeassistant.

my docker-compose.yml:

```
 services:
  ebusd:
    # alternatively, use "john30/ebusd:devel" for the latest build of the current source code
    image: john30/ebusd
    container_name: ebusd
    restart: unless-stopped
    ports:
      - 8888:8888
      # when enabling the HTTP port, add it to the published ports as well:
      #- 8080:8080
    #devices:
      # when using an USB device, make sure to hand it in to the container like this:
      # - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      # Device options:

      # Use DEV as eBUS device:
      # - "mdns:" for auto discovery via mDNS with optional suffix "[ID][@INTF]" for using a specific hardware ID
      #   and/or IP interface INTF for the discovery (only for eBUS Adapter Shield; on docker, the network device
      #   needs to support multicast routing e.g. like the host network), or
      # - prefix "ens:" for enhanced high speed device,
      # - prefix "enh:" for enhanced device, or
      # - no prefix for plain device, and
      # - suffix "IP[:PORT]" for network device, or
      # - suffix "DEVICE" for serial device
      EBUSD_DEVICE: "ens:192.168.178.12:9999"
      # Skip serial eBUS device test
      #EBUSD_NODEVICECHECK: ""
      # Only read from device, never write to it
      #EBUSD_READONLY: ""
      # Send an initial escape symbol after connecting device
      #EBUSD_INITSEND: ""
      # Extra transfer latency in ms
      EBUSD_LATENCY: 10

      # Message configuration options:

      # Read CSV config files from PATH (local folder or HTTPS URL)
      EBUSD_CONFIGPATH: "/config"
      # Pick CSV config files matching initial scan.
      # - empty for broadcast ident message (default when EBUSD_CONFIGPATH is not given),
      # - "none" for no initial scan message,
      # - "full" for full scan,
      # - a single hex address to scan, or
      # - "off" for not picking CSV files by scan result (default when EBUSD_CONFIGPATH is given).
      EBUSD_SCANCONFIG: "full"
      # Retry scanning devices COUNT times
      #EBUSD_SCANRETRIES: 5
      # Prefer LANG in multilingual configuration files
      #EBUSD_CONFIGLANG: "en"
      # Poll for data every SEC seconds (0=disable)
      #EBUSD_POLLINTERVAL: 10
      # Use CA FILE for checking certificates (uses defaults, "#" for insecure)
      #EBUSD_CAFILE: "/path/to/cafile"
      # Use CA PATH for checking certificates (uses defaults)
      #EBUSD_CAPATH: "/path/to/cafiles"

      # eBUS options:

      # Use hex ADDR as own master bus address
      #EBUSD_ADDRESS: "ff"
      # Actively answer to requests from other masters
      #EBUSD_ANSWER: ""
      # Stop bus acquisition after MSEC ms
      #EBUSD_ACQUIRETIMEOUT: 10
      # Retry bus acquisition COUNT times
      #EBUSD_ACQUIRERETRIES: 3
      # Repeat failed sends COUNT times
      #EBUSD_SENDRETRIES: 2
      # Expect a slave to answer within MSEC ms
      #EBUSD_RECEIVETIMEOUT: 50
      # Expect COUNT masters on the bus, 0 for auto detection
      #EBUSD_NUMBERMASTERS: 0
      # Enable AUTO-SYN symbol generation
      #EBUSD_GENERATESYN: ""

      # Daemon options:

      # Set default access level to LEVEL ("*" for everything)
      #EBUSD_ACCESSLEVEL: "*"
      # Read access control list from FILE
      #EBUSD_ACLFILE: "/path/to/aclfile"
      # Enable hex/inject/answer commands
      #EBUSD_ENABLEHEX: ""
      # Enable define command
      #EBUSD_ENABLEDEFINE: ""
      # PID file name (only for daemon)
      #EBUSD_PIDFILE: "/var/run/ebusd.pid"
      # Listen for command line connections on PORT
      #EBUSD_PORT: 8888
      # Listen for command line connections on 127.0.0.1 interface only
      #EBUSD_LOCALHOST: ""
      # Listen for HTTP connections on PORT, 0 to disable
      #EBUSD_HTTPPORT: 8080
      # Path for HTML files served by HTTP port
      #EBUSD_HTMLPATH: "/var/ebusd/html"
      # Set automatic update check to MODE (on|off)
      #EBUSD_UPDATECHECK: "on"

      # Log options:

      # Write log to FILE (only for daemon, empty string for using syslog)
      EBUSD_LOGFILE: "/var/log/ebusd.log"
      # Only write log for matching AREA(S) up to LEVEL (alternative to EBUSD_LOGAREAS/EBUSD_LOGLEVEL, may be used
      # multiple times)
      EBUSD_LOG: "all:notice"
      # Only write log for matching AREA(S): main|network|bus|device|update|other|all
      EBUSD_LOGAREAS: "all"
      # Only write log up to LEVEL: error|notice|info|debug
      EBUSD_LOGLEVEL: "notice"

      # Raw logging options:

      # Log messages or all received/sent bytes on the bus
      #EBUSD_LOGRAWDATA: ""
      # Write raw log to FILE
      #EBUSD_LOGRAWDATAFILE: "/var/log/ebusd.log"
      # Make raw log file no larger than SIZE kB
      #EBUSD_LOGRAWDATASIZE: 100

      # Binary dump options:

      # Enable binary dump of received bytes
      #EBUSD_DUMP: ""
      # Dump received bytes to FILE
      #EBUSD_DUMPFILE: "/tmp/ebusd_dump.bin"
      # Make dump file no larger than SIZE kB
      #EBUSD_DUMPSIZE: 100
      # Flush each byte
      #EBUSD_DUMPFLUSH: ""

      # MQTT options:

      # Connect to MQTT broker on HOST
      EBUSD_MQTTHOST: "192.168.178.5"
      # Connect to MQTT broker on PORT (usually 1883), 0 to disable
      EBUSD_MQTTPORT: 1883
      # Set client ID for connection to MQTT broker
      #EBUSD_MQTTCLIENTID: "ebusd"
      # Connect as USER to MQTT broker (no default)
      EBUSD_MQTTUSER: "dirkt"
      # Use PASSWORD when connecting to MQTT broker (no default)
      EBUSD_MQTTPASS: "dirkt"
      # Use MQTT TOPIC (prefix before /%circuit/%name or complete format)
      EBUSD_MQTTTOPIC: "ebusd"
      # Use TOPIC for global data (default is "global/" suffix to mqtttopic prefix)
      #EBUSD_MQTTGLOBAL: "ebusd/global/"
      # Retain all topics instead of only selected global ones
      #EBUSD_MQTTRETAIN: ""
      # Set the QoS value for all topics (0-2)
      #EBUSD_MQTTQOS: 0
      # Read MQTT integration settings from FILE (no default)
      EBUSD_MQTTINT: "mqtt-hassio.cfg"
      # Add variable(s) to the read MQTT integration settings (append to already existing value with "NAME+=VALUE")
      #EBUSD_MQTTVAR: "key[+]=value[,...]"
      # Publish in JSON format instead of strings, optionally in short (value directly below field key)
      #EBUSD_MQTTJSON: ""
      # Publish all available attributes
      #EBUSD_MQTTVERBOSE: ""
      # Log library events
      #EBUSD_MQTTLOG: ""
      # Use protocol VERSION
      #EBUSD_MQTTVERSION: "3.1"
      # Ignore invalid parameters during init (e.g. for DNS not resolvable yet)
      #EBUSD_MQTTIGNOREINVALID: ""
      # Whether to only publish changed messages instead of all received
      #EBUSD_MQTTCHANGES: ""
      # Use CA file or dir (ending with '/') for MQTT TLS (no default)
      #EBUSD_MQTTCA: "/path/to/cafile"
      # Use CERTFILE for MQTT TLS client certificate (no default)
      #EBUSD_MQTTCERT: "/path/to/certfile"
      # Use KEYFILE for MQTT TLS client certificate (no default)
      #EBUSD_MQTTKEY: "/path/to/keyfile"
      # Use PASSWORD for the encrypted KEYFILE (no default)
      #EBUSD_MQTTKEYPASS: "some-passwort"
      # Allow insecure TLS connection (e.g. using a self signed certificate)
      #EBUSD_MQTTINSECURE: ""
```

My folder on homeserver are:
![image](https://github.com/user-attachments/assets/15284ac7-0d91-404f-94c0-e4f2eecff2e4)

![image](https://github.com/user-attachments/assets/e1a2826b-dc4b-4c9d-bdbb-824c880f749b)

In the log there is also mentioned that the config files and the mqtt-hassio.cfg are not found?! So I think there is something wrong with my docker-compose.yml

```
dirk@Homeserver:/mnt/ssd/ebusd$ docker compose up
[+] Running 1/1
 ✔ Container ebusd  Recreated                                                                                      0.2s
Attaching to ebusd
ebusd  | invalid log (combined with logareas or loglevel)
ebusd  | 2025-02-22 14:01:23.342 [main notice] invalid/unknown argument in env (ignored): EBUSD_LOG=all
ebusd  | 2025-02-22 14:01:23.346 [device notice] transport opened
ebusd  | 2025-02-22 14:01:23.346 [mqtt error] unable to open integration file ./mqtt-hassio.cfg
ebusd  | 2025-02-22 14:01:23.347 [main notice] ebusd 24.1.24.1 started with broadcast scan on device: 192.168.178.12:9999, TCP, enhanced
ebusd  | 2025-02-22 14:01:23.347 [main error] error reading config files from /config/: ERR: element not found, last error:
ebusd  | 2025-02-22 14:01:23.347 [bus notice] bus started with own address 31/36
ebusd  | 2025-02-22 14:01:23.348 [mqtt notice] connection established
ebusd  | 2025-02-22 14:01:23.349 [device notice] reset, supports info
ebusd  | 2025-02-22 14:01:23.351 [device notice] extra info: firmware 1.1[5210].1[5210], jumpers 0x0b
ebusd  | 2025-02-22 14:01:23.391 [bus notice] signal acquired
ebusd  | 2025-02-22 14:01:23.425 [bus notice] new master 10, master count 2
ebusd  | 2025-02-22 14:01:23.462 [bus notice] new master 03, master count 3
ebusd  | 2025-02-22 14:01:23.463 [update notice] received unknown MS cmd: 1008b5110102 / 050000c800c8
ebusd  | 2025-02-22 14:01:23.613 [update notice] received unknown MS cmd: 1050b5040133 / 02a00b
ebusd  | 2025-02-22 14:01:26.276 [update notice] received unknown MS cmd: 1025b509040ef40000 / 00
ebusd  | 2025-02-22 14:01:26.732 [update notice] received unknown MS cmd: 1008b5130304cd01 / 0acd010100000001000100
ebusd  | 2025-02-22 14:01:26.908 [update notice] received unknown MS cmd: 1008b5100900023e000000000002 / 00
ebusd  | 2025-02-22 14:01:27.283 [update notice] received unknown MS cmd: 1008b509040ed10001 / 00
ebusd  | 2025-02-22 14:01:28.738 [update notice] received unknown MS cmd: 1050b5040101 / 091b0300000085000100
ebusd  | 2025-02-22 14:01:28.906 [update notice] received unknown MS cmd: 1050b504020d00 / 051f00dc011b
ebusd  | 2025-02-22 14:01:29.090 [update notice] received unknown MS cmd: 1050b5040132 / 0a002206030101a00b0100
ebusd  | 2025-02-22 14:01:29.241 [update notice] received unknown MS cmd: 1050b5040131 / 020001
ebusd  | 2025-02-22 14:01:32.724 [update notice] received unknown BC cmd: 10feb5050427001d00
ebusd  | 2025-02-22 14:01:32.857 [update notice] received unknown BC cmd: 10feb505034a0100
ebusd  | 2025-02-22 14:01:33.347 [main notice] starting initial broadcast scan
ebusd  | 2025-02-22 14:01:33.911 [update notice] sent unknown BC cmd: 31fe07fe00
ebusd  | 2025-02-22 14:01:33.950 [update notice] received unknown BC cmd: 10fe07ff0100
ebusd  | 2025-02-22 14:01:34.023 [bus notice] new master 3f, master count 4
ebusd  | 2025-02-22 14:01:34.023 [update notice] received unknown BC cmd: 3ffe07ff00
ebusd  | 2025-02-22 14:01:34.493 [bus notice] new master 7f, master count 5
ebusd  | 2025-02-22 14:01:34.493 [update notice] received unknown BC cmd: 7ffe07ff00
ebusd  | 2025-02-22 14:01:34.748 [update notice] received unknown MS cmd: 1050b505072b000100000000 / 00
ebusd  | 2025-02-22 14:01:34.937 [update notice] received unknown MS cmd: 1008b511020300 / 0ad8017806dd0303280000
ebusd  | 2025-02-22 14:01:35.100 [update notice] received unknown MS cmd: 1008b5110102 / 050000c800c8
ebusd  | 2025-02-22 14:01:37.244 [update notice] received unknown MS cmd: 1008b5090329b801 / 03b80100
ebusd  | 2025-02-22 14:01:37.406 [update notice] received unknown MS cmd: 1008b5090329b901 / 03b90100
ebusd  | 2025-02-22 14:01:37.578 [update notice] received unknown MS cmd: 1008b50903290f00 / 050f00480000
ebusd  | 2025-02-22 14:01:37.741 [update notice] received unknown MS cmd: 1008b5090329bb00 / 03bb0000
ebusd  | 2025-02-22 14:01:37.905 [update notice] received unknown MS cmd: 1008b5090329ba00 / 03ba0000
ebusd  | 2025-02-22 14:01:38.001 [bus notice] max. symbols per second: 101
ebusd  | 2025-02-22 14:01:38.068 [update notice] received unknown MS cmd: 1008b5090329e201 / 03e20136
ebusd  | 2025-02-22 14:01:38.239 [update notice] received unknown MS cmd: 1008b50903290300 / 050300dc0100
ebusd  | 2025-02-22 14:01:38.812 [update notice] received unknown MS cmd: 1008b5100900023e000000000002 / 00
```
