### DISCUSSION TITLE
Selection of polled data?

### DISCUSSION THREAD

**Discussion by ahemwe** [john30/ebusd#1499] [General]
Hi,

I've connected an ebusd device to Home Assistant via MQTT.

When monitoring the published MQTT topics, I notice some unexpected behavior:

Some topics are published even though I have never polled them (neither via MQTT nor ebusctl).
Some topics appear very infrequently (only every few hours).
To address this, I set up an automation in Home Assistant to periodically trigger the get command with a polling priority:

``` yaml
- id: '1729016246052'
  alias: ebus Update
  description: ''
  triggers:
  - trigger: time_pattern
    hours: /3
  conditions: []
  actions:
  - action: mqtt.publish
    metadata: {}
    data:
      topic: ebusd/ctlv2/Z1OpMode/get
      payload: ?1
  - action: mqtt.publish
    metadata: {}
    data:
      topic: ebusd/bai/Flame/get
      payload: ?1
  - action: mqtt.publish
    metadata: {}
    data:
      topic: ebusd/ctlv2/Z1ActualRoomTempDesired/get
      payload: ?3
  - action: mqtt.publish
    metadata: {}
    data:
      topic: ebusd/bai/ModulationTempDesired/get
      payload: ?1
  - action: mqtt.publish
    metadata: {}
    data:
      topic: ebusd/bai/OutdoorstempSensor/get
      payload: ?3
  - action: mqtt.publish
    metadata: {}
    data:
      topic: ebusd/bai/FlowTempDesired/get
      payload: ?3
  - action: mqtt.publish
    metadata: {}
    data:
      topic: ebusd/bai/SetMode/get
      payload: ?3
    enabled: false
  mode: single
```

With this setup, I expect bai/Flame to be updated as frequently as possible, while other topics may update less often.

However, what I observe is:

The temperature reported by ebusd/bai/Status01 (which I never explicitly requested) decreases, while bai/Flame does not update to "off" as expected.
I see frequent updates for unrelated topics like`ebusd/ctlv2/Z3SFMode`, even though I don’t have a Z3 circuit at all.

My Questions:
* Is my approach of actively polling messages correct?
* Could these unintended messages be blocking the queue?
* Can I prevent the device from polling or publishing these unwanted topics?

Thanks a lot for your help!
