### DISCUSSION TITLE
Home Assistant: HVAC entity

### DISCUSSION THREAD

**Discussion by wlcrs** [john30/ebusd#530] [Show and tell]
Following the native HA-integration of john30, I adapted the configuration of my [MQTT HVAC](https://www.home-assistant.io/integrations/climate.mqtt/) entity as follows:

```
climate:
  - platform: mqtt
    name: CV
    max_temp: 25
    min_temp: 15
    precision: 0.1
    temp_step: 0.5

    action_topic: "ebusd/bai/Status01"
    action_template: "{{ (value_json['5'].value == 'on') | iif('heating', 'idle') }}"
    modes:
      - auto
      - heat
      - cool
      - "off"
    mode_state_template: >-
      {% set mode_values = { 'auto':'auto', 'on':'heat',  'night':'cool', 'summer':'off'} %}
      {{ mode_values[value_json['0'].value] | default('off') }}
    mode_state_topic: "ebusd/35000/Hc1OPMode"
    mode_command_template: >-
      {% set values = { 'auto':'auto', 'heat':'on',  'cool':'night', 'off':'summer'} %}
      {{ values[value] | default('auto') }}
    mode_command_topic: "ebusd/35000/Hc1OPMode/set"
    value_template: "{{ value_json.temp1.value }}"
    temperature_state_topic: "ebusd/35000/DisplayedHc1RoomTempDesired"
    temperature_low_state_topic: "ebusd/35000/Hc1NightTemp"
    temperature_high_state_topic: "ebusd/35000/Hc1DayTemp"

    temperature_low_command_topic: "ebusd/35000/Hc1NightTemp/set"
    temperature_high_command_topic: "ebusd/35000/Hc1DayTemp/set"
    current_temperature_topic: "ebusd/35000/DisplayedRoomTemp"
    current_temperature_template: "{{ value_json.temp.value }}"

```

This results in the following entity becoming available in the Lovelace interface:
![image](https://user-images.githubusercontent.com/2150060/153829119-30c841df-f953-4df3-a9e1-aa4d53c66cd2.png)

Note that I abuse the HA thermostat slightly by setting the night temperature as "low temperature" in this entity. Normally you only set the "low temperature" if you have a device that can both heat and cool your place to keep it within the stated temperature range.

**Comment by pepsonEL** [comment]
Hi
I created thermostat as you for my heating but no working. Nothing show....

```
- platform: mqtt
  name: Parter podłogówka
  max_temp: 30
  min_temp: 5
  precision: 0.1
  temp_step: 0.5
  modes:
    - auto
    - heat
    - cool
    - "off"
  mode_state_template: >-
    {% set mode_values = { 'auto':'auto', 'day':'heat',  'night':'cool', 'off':'off'} %}
    {{ mode_values[value_json['0'].value] | default('off') }}
  mode_state_topic: "ebusd/700/z2OpMode"
  mode_command_template: >-
    {% set values = { 'auto':'auto', 'heat':'day',  'cool':'night', 'off':'off'} %}
    {{ values[value] | default('auto') }}
  mode_command_topic: "ebusd/700/z2OpMode/set"
  value_template: "{{ value_json.temp1.value }}"
  temperature_state_topic: "ebusd/700/z2ActualRoomTempDesired"
  temperature_low_state_topic: "ebusd/700/z2NightTemp"
  temperature_high_state_topic: "ebusd/700/z2DayTemp"
  temperature_low_command_topic: "ebusd/700/z2NightTemp/set"
  temperature_high_command_topic: "ebusd/700/z2DayTemp/set"
  current_temperature_topic: "ebusd/700/z2RoomTemp"
  current_temperature_template: "{{ value_json.temp.value }}"
```
![thermo](https://user-images.githubusercontent.com/71824185/154331916-db8b2902-a691-4ee2-8149-d7543a4c0e97.jpg)


I dont know why... maybe anybody can help me please.

**Reply by Koky05** [reply]
Try MQTT explorer and check what values you get into MQTT.

**Reply by KoksaJanosch** [reply]
problem solved? I have the same problem, btw I receive values through MQTT explorer.

**Reply by Koky05** [reply]
@KoksaJanosch can you post data hierarchy which you see in MQTT Explorer?

![image](https://github.com/john30/ebusd/assets/89223022/24b12868-0d0b-45e2-95f7-3a1a847cbe25)

**Reply by KoksaJanosch** [reply]
Sure, here it is:) 

![mqtt2](https://github.com/john30/ebusd/assets/41262319/8127b0b5-e1bb-4d1e-81aa-d0dfa66042a4)
![mqtt](https://github.com/john30/ebusd/assets/41262319/f7d2e41e-aab9-4093-a64c-1500c0432339)

**Reply by Koky05** [reply]
@KoksaJanosch I wrote you on FB messanger. It will be faster and in our language.

**Comment by eiabea** [comment]
@wlcrs thank you for the config, this got my mode setting to work. I had a hard time debugging the json objects. Unfortunately the temperature setting only shows 1 circle which always snaps back to 0

![image](https://github.com/john30/ebusd/assets/688128/8ff706c6-050f-42ef-9085-25defba16ba5)

PS: Sorry for heating up such an old discussion

**Reply by eiabea** [reply]
Never mind, i had the `min_temp` set to i higher value than my heater published over mqtt :unamused:

**Comment by dMopp** [comment]
Hi, i always getting that error in the log:

2024-11-08T23:26:34.389624+01:00 ulli01 homeassistant[779]: #033[33m2024-11-08 23:26:34.387 WARNING (MainThread) [homeassistant.components.mqtt.climate] Invalid ['cooling', 'defrosting', 'drying', 'fan', 'heating', 'idle', 'off', 'preheating'] action: day#033[0m

Any idea?

My Config:
```
climate:
    - name: "Vaillant EcoTEC Plus"
      unique_id: vaillant_ecotec_plus
      max_temp: 25
      min_temp: 18
      temp_step: 0.5
      precision: 0.1
      modes:
        - auto
        - heat
        - cool
        - "off"
      action_topic: "ebusd/700/Z1OpMode"
      action_template: "{{ value_json.value.value }}"
      mode_state_template: >-
        {% set values = { 'auto':'auto', 'on':'heat',  'night':'cool', 'summer':'off'} %}
        {{ values[value] if value in values.keys() else 'off' }}
      mode_state_topic: "ebusd/700/Z1OpMode"
      mode_command_template: >-
        {% set values = { 'auto':'auto', 'heat':'on',  'cool':'night', 'off':'summer'} %}
        {{ values[value] if value in values.keys() else 'auto' }}
      mode_command_topic: "ebusd/700/Z1OpMode/set"
      temperature_state_topic: "ebusd/700/Z1ActualRoomTempDesired"
      temperature_high_state_template: "{{ value_json.value.value }}"
      temperature_low_state_template: "{{ value_json.value.value }}"
      temperature_low_state_topic: "ebusd/700/Z1NightTemp"
      temperature_high_state_topic: "ebusd/700/Z1DayTemp"
      temperature_low_command_topic: "ebusd/700/Z1NightTemp/set"
      temperature_high_command_topic: "ebusd/700/Z1DayTemp/set"
      current_temperature_topic: "homeassistant/sensor/durchschnittliche_raumtemperatur"
      current_temperature_template: "{{ value_json }}"
```

**Reply by Koky05** [reply]
Action topic has also only couple of allowed values.
I translated them same way as states.
Allowed are: `off, heating, cooling, drying, idle, fan`.

**Reply by dMopp** [reply]
I don’t get it, how should the yaml look? Thanks

**Reply by Koky05** [reply]
```
climate:
    - name: "Vaillant EcoTEC Plus"
      unique_id: vaillant_ecotec_plus
      max_temp: 25
      min_temp: 18
      temp_step: 0.5
      precision: 0.1
      modes:
        - auto
        - heat
        - cool
        - "off"
      action_topic: "ebusd/700/Z1OpMode"
      action_template: >-
        {% set values = { 'on':'heating', 'off':'idle', 'hwc':'fun' } %}
        {{ values[value] if value in values.keys() else 'off' }}
      mode_state_template: >-
        {% set values = { 'auto':'auto', 'on':'heat',  'night':'cool', 'summer':'off'} %}
        {{ values[value] if value in values.keys() else 'off' }}
      mode_state_topic: "ebusd/700/Z1OpMode"
      mode_command_template: >-
        {% set values = { 'auto':'auto', 'heat':'on',  'cool':'night', 'off':'summer'} %}
        {{ values[value] if value in values.keys() else 'auto' }}
      mode_command_topic: "ebusd/700/Z1OpMode/set"
      temperature_state_topic: "ebusd/700/Z1ActualRoomTempDesired"
      temperature_high_state_template: "{{ value_json.value.value }}"
      temperature_low_state_template: "{{ value_json.value.value }}"
      temperature_low_state_topic: "ebusd/700/Z1NightTemp"
      temperature_high_state_topic: "ebusd/700/Z1DayTemp"
      temperature_low_command_topic: "ebusd/700/Z1NightTemp/set"
      temperature_high_command_topic: "ebusd/700/Z1DayTemp/set"
      current_temperature_topic: "homeassistant/sensor/durchschnittliche_raumtemperatur"
      current_temperature_template: "{{ value_json }}"
```

**Reply by dMopp** [reply]
many thanks !

This is my config now:

```
mqtt:
  ###Heizung
  climate:
    - name: "Vaillant EcoTEC Plus"
      unique_id: vaillant_ecotec_plus
      max_temp: 25
      min_temp: 18
      temp_step: 0.5
      precision: 0.1
      modes:
        - auto
        - heat
        - cool
        - "off"
      action_topic: "ebusd/700/Z1OpMode"
      #action_template: "{{ value_json.value.value }}"
      action_template: >-
        {% set values = { 'day':'heating', 'off':'off', 'auto':'auto' , 'night':'cooling' } %}
        {{ values[value] if value in values.keys() else 'off' }}
      mode_state_template: >-
        {% set values = { 'auto':'auto', 'day':'heat', 'night':'cool', 'off':'off'} %}
        {% set state = value_json.value.value %}
        {{ values[state] if state in values.keys() else 'off' }}
      mode_state_topic: "ebusd/700/Z1OpMode"
      mode_command_template: >-
        {% set values = { 'auto':'auto', 'heat':'day', 'cool':'night', 'off':'off'} %}
        {{ values[value] if value in values.keys() else 'auto' }}
      mode_command_topic: "ebusd/700/Z1OpMode/set"
      current_temperature_topic: "homeassistant/sensor/durchschnittliche_raumtemperatur"
      current_temperature_template: "{{ value_json }}"
      temperature_state_topic: "ebusd/700/Z1ActualRoomTempDesired"
      temperature_low_state_template: "{{ value_json.value.value }}"
      temperature_low_state_topic: "ebusd/700/Z1NightTemp"
      temperature_low_command_topic: "ebusd/700/Z1NightTemp/set"
      temperature_high_state_template: "{{ value_json.value.value }}"
      temperature_high_state_topic: "ebusd/700/Z1DayTemp"
      temperature_high_command_topic: "ebusd/700/Z1DayTemp/set"

    ###Warmwasser
    - name: "Vaillant EcoTEC Plus Warmwasser"
      unique_id: vaillant_ecotec_plus_warmwasser
      max_temp: 90
      min_temp: 45
      temp_step: 1
      precision: 0.1
      action_topic: "ebusd/700/HwcOpMode"
      action_template: "{{ value_json.value.value }}"
      modes:
        - auto
        - "off"
      mode_state_template: >-
        {% set values = { 'auto':'auto', 'off':'off'} %}
        {{ values[value] if value in values.keys() else 'auto' }}
      mode_state_topic: "ebusd/700/HwcOpMode"
      mode_command_template: >-
        {% set values = { 'auto':'auto', 'off':'off'} %}
        {{ values[value] if value in values.keys() else 'auto' }}
      mode_command_topic: "ebusd/700/HwcOpMode/set"
      temperature_high_state_template: "{{ value_json.value.value }}"
      temperature_high_state_topic: "ebusd/700/HwcTempDesired"
      temperature_high_command_topic: "ebusd/700/HwcTempDesired/set"
      current_temperature_topic: "ebusd/vr_71/SensorData1"
      current_temperature_template: "{{ value_json.s5.value }}"
```

**Reply by Koky05** [reply]
I prefere `idle` instead of `off`. Off turning off device, idle is switching to auto mode. But I have combiHeater with boiler ecoCompact VSC and thermostat CalorMatic 470F.

**Reply by dMopp** [reply]
I would agree, but iam changing the action of Z1 and not touching the boiler in that case.

**Comment by jflkjjlkdsajlkdsajlkjlkjdsaljdsa** [comment]
Hello,

I'm reaching out because I'm experiencing recurring issues with my Home Assistant HVAC configuration. It was functioning perfectly initially, but it keeps breaking after some time, and I'm unable to pinpoint the cause. It seems that recent updates to Home Assistant might have disrupted it once again.

I've already verified the MQTT topics using MQTT Explorer, and everything appears to be correctly set up. However, despite this, my thermostat is still not working as expected. Could you please provide some guidance or suggestions on what might be going wrong or what I should check next?
Currently it looks like this: 
![image](https://github.com/user-attachments/assets/7d6a8c24-b1ad-4b9e-940c-e0b914c22c56)

My configuration looks like this:
```

mqtt:
  climate:
    name: CV
#    availability:
#        topic: "ebusd/global/signal"
#        payload_available: true
#        payload_not_available: false
    max_temp: 25
    min_temp: 15
    precision: 0.1
    temp_step: 0.5
    action_topic: "ebusd/bai/Status01"
    action_template: "{{ (value_json['5'].value == 'on') | iif('heating', 'idle') }}"
    mode_state_topic: "ebusd/370/Hc1OPMode"
    modes:  ["auto", "off", "cool", "heat"]
    mode_state_template: >-
      {% set mode_values = { 'auto':'auto', 'on':'heat', 'night':'cool', 'summer':'off' } %}
      {{ mode_values.get(value_json['0'].value, 'off') }}
    mode_command_template: >-
      {% set values = { 'auto':'auto', 'heat':'on', 'cool':'night', 'off':'summer' } %}
      {{ values.get(value, 'auto') }}
    mode_command_topic: "ebusd/370/Hc1OPMode/set"
    current_temperature_topic: "ebusd/370/DisplayedRoomTemp"
    current_temperature_template: '{{value_json["value"].value}}'
    temperature_low_state_topic: "ebusd/370/Hc1NightTemp"
    temperature_high_state_topic: "ebusd/370/Hc1DayTemp"
    temperature_low_command_topic: "ebusd/370/Hc1NightTemp/set"
    temperature_high_command_topic: "ebusd/370/Hc1DayTemp/set"
    temperature_command_topic: "ebusd/370/Hc1DayTemp/set"
#    temperature_state_topic: "ebusd/370/Hc1DayTemp"
#    json_attributes_template: '{{value_json["value"].value}}'
```
