### DISCUSSION TITLE
How to emulate controller

### DISCUSSION THREAD

**Discussion by luzik** [john30/ebusd#719] [Q&A]
Is it possible to emulate temperature controller like Calormatic 450?

I want to report lowest temperature in home rooms.

What does Calormatic do ? Is it actively report:
- room temperature
- temperature set
- heat curve
- schedule
Or just respond to EcoTEC as a slave?

Or maybe Calormatic does calculate FlowTempDesired
Does anybody know formula to calculate FlowTempDesired ?

**Comment by k41c** [comment]
Hi luzik,

on my boiler I need to set the boiler temperature to max. So the controller will send commands to stop the boiler heating when not needed. The controler get the feedback of the heatingwater temperature and will controll it by calculation, in my case, by outside temperature and heatcurve. If you have a room temperature then this will overdrive the previusly calculated value if its to warm or cold. Allso dont forget the start and stop ramps if you are using a night reduced temperature e.g. 18°C.
At the moment I can't tell if its master-master or master-slave comunication. But I will report as far as I'm ready with my adapter. My plan is to simulate a roomtemperature. And switch to different rooms as reference, so day its livingroom and night sleeping room.

**Comment by PureDJ** [comment]
I have a ColorMatic 360 and I have successfully taken over control, actually in both ways.
I made my own controller with PID, outside temp (with a heating curve), away mode, schedule with early start (room is at decired temp when the schedule is set, not start heating when the schedule start), delayed lower temp when the TV is on etc.

I can set the control function into 2 modes, tell the ColorMatic what temp I want and let it handle the controls (in my case more gas consumption, because it only know 2 modes, full heat or no heat) or let my own PID controller do the work and read out the actual temp.

I'm not sure what you want to do.
But telling the ColorMatic the desired temp you can do with writing ComfTempDesired
If you want full control you can set OperatingMode to 0, but be carefull! you need to write SetMode(override) at least every second otherwise the heater will switch to on/off thermostat mode and Valiant is telling users to have a wire loop over the contact input it will put your heater in full on!
 
 Hope this helps.

**Comment by ostauss** [comment]
Dear @PureDJ, 
I'm really interested in the details of your topic “create own controller”. 
Currently, I “control the controller (f37)” but I want to “replace” this simple controller with an advanced (outside, heating curve, etc). 
Maybe you can share your “learnings”? 
(i also use node-red...)
regards Oliver

**Comment by netweaver1970** [comment]
@PureDJ I'm also very interested in your own implementation. Right now I have a Migo (Bulex/Vaillant rebranded Netatmo smart thermostat), which has internet based outside temp supply, heating curve setup, self learning PID parameters, pre-heating etc.. I'm controlling the Migo via HomeAssisant, using the Bulex Cloud service. And I have Zigbee TRVs on my radiators. As such I'm not unhappy with the Migo factory+ HA + Smart TRVs solution but I'm always interested in seeing how other people solved it, in case it's better. My eBus adapter + HA integration is currently more a monitoring and (if needed/ deemed better/valuable) a 
way to take control of the system.

**Comment by PureDJ** [comment]
Funny thing my HA crashed, so I'm setting up everything at the moment, it's been a while, but what I have accomplished is a complete PID controller, outside temp I could not read out, but I used a weather forcast site to get the actual outside temp.
I'm going to rewrite some controllers, I found out that my automatic temp lowering not always worked correctly (I use my wifi router to check if one of our families phone is connected to the wifi, if not, it lowers the setpoint 1 degree, if it has been lowered and one phone is connected, it raises the setpoint temp by 1 degree (celcius)
I can share the node red setup if you want, but let me correct it first, it's a bit messy now

**Comment by john30** [comment]
I was forced to do something similar a couple of years ago as my heat pump controller crashed and I was not able to get it back to life. did a lot of replaying recorded messages from before its death but I could not convince the heat pump to do something useful. really awful. so, just wanted to mention that it seems to be one of the most complicated and challenging tasks and I more or less gave up (and ended in buying a new controller)

**Comment by PureDJ** [comment]
I'm working on it right now, cleanup the Node Red stuff, to make it better serviceable.

The system is complex and I wrote it for my application, but I can help if I know what you want to do?
In my case I run Home Assistant on a server.
I have a raspberry pi with a own made EBUS controller PCB
On the Raspberry I have EBUSD running and some scripts to request information from the boiler and thermostat.
On the raspberry pi I have Mosquito MQTT running forwarding the info to Home Assistant's Mosquito
I have also a ESP8266 sensor with MQTT to measure the temp.  
In Home Assistant I have a scheduler and a Nest lookalike Temp controller, everything is picked up in Node Red and there everything is processed.

Please tell me about your setup, so Maybe I can help out

**Comment by ostauss** [comment]
Hi, sounds really interesting. 
I started with ebusd in a simple way. With node-red I wrote a UI to control the controller F37.  Works fine, but does not fit my requirements. 
Independent of the vaillant System, I have temp sensors in every room (and outdoor). 

My basic idea was to implement my own thermostat – using all temp sensors to control the vaillant and also additionally (later) control each radiator. 
I think your project is a good starting point – learning how to emulate a vaillant thermostat.
* Which messages are relevant? 
* What pitfalls needs to be taken care, “emulate” a controller?
* What kind of scripts do you use to request information from boiler? (isn't it all by default on MQTT?)
* anything else you really learned during the project, *lol* :-)

If someone is interested, I can share my node-red implementation of "control the controller F37". 

Regards Oliver

**Comment by luzik** [comment]
This is my way of controlling Calormatic from Home Assistant

mqtt.yaml

```
climate:
  - name: Vaillant
    unique_id: Vaillant
    device:
      identifiers: "ebusd_bai"
      via_device: "ebusd"
    max_temp: 25
    min_temp: 15
    #precision: 0.1
    temp_step: 0.5
    action_topic: "ebusd/bai/WP"
    action_template: "{{ 'heating' if value_json['onoff']['value'] == 'on' else 'idle' }}"
    modes:
     - auto
     - heat
     - cool
     - 'off'
    mode_state_template: >-
      {% set values = { 'auto':'auto', 'on':'heat', 'night':'cool', 'summer':'off'} %}
      {{ values[value_json['0']['value']] if value_json['0']['value'] in values.keys() else 'off' }}
    mode_state_topic:  "ebusd/450/Hc1OPMode"
    mode_command_template: >-
      {% set values = { 'auto':'auto', 'heat':'on', 'cool':'night', 'off':'summer'} %}
      {{ values[value] if value in values.keys() else 'auto' }}
    mode_command_topic: "ebusd/450/Hc1OPMode/set"
    temperature_state_template: "{{value_json['temp1']['value']}}"
    temperature_state_topic: "ebusd/450/DisplayedHc1RoomTempDesired"
    temperature_low_state_template: "{{value_json['temp1']['value']}}"
    temperature_low_state_topic: "ebusd/450/Hc1NightTemp"
    temperature_high_state_template: "{{value_json['temp1']['value']}}"
    temperature_high_state_topic: "ebusd/450/Hc1DayTemp"
    temperature_low_command_topic: "ebusd/450/Hc1NightTemp/set"
    temperature_high_command_topic: "ebusd/450/Hc1DayTemp/set"
    current_temperature_template: "{{value_json['temp']['value']}}"
    current_temperature_topic: "ebusd/450/DisplayedRoomTemp"
```

I've got also a lot of sensors and binary_sensors definition with corresponding UI if someone is interested.
While emulating controller is nice option to have, after few consideration I will leave controller connected, but will automate controller temperature set to following rules:


largest_room_temp_diff = set_room_temp - measured_room_temp ..largest diff found across all rooms
controller_temp = temperature reported by vaillant controller
controller_set_temp = controller_temp + largest_room_temp_diff

Temperature in rooms is controlled by home assistant using generic_thermostat with valves and temperature sensors in all rooms. FlowTempDesired is controlled by Vaillant Calormatic that is using heat curve, controller_temp and controller_set_temp
![Zrzut ekranu z 2022-11-18 10 05 41](https://user-images.githubusercontent.com/6113774/202665416-f4252a71-0a0e-4973-b5ec-532eb29c2742.png)
![Zrzut ekranu z 2022-11-18 10 06 56](https://user-images.githubusercontent.com/6113774/202665420-67bc9186-8aef-400a-a2e1-cf0f21e76891.png)
![Zrzut ekranu z 2022-11-18 10 12 46](https://user-images.githubusercontent.com/6113774/202665422-1c70487d-885c-4633-83a7-0491b288105b.png)
