### DISCUSSION TITLE
Config thermostat

### DISCUSSION THREAD

**Discussion by Achy7** [john30/ebusd#764] [General]
Hello all,

```
climate:
  name: Termostato 380 Valliant
  max_temp: 30
  min_temp: 5
  precision: 0.1
  temp_step: 0.5
  modes:
   - auto
   - heat
   - cool
   - 'off'
  mode_state_template: >-
    {% set values = { 'auto':'auto', 'day':'heat', 'night':'cool', 'off':'off'} %}
    {% set state = value_json["opmode"].value %}
    {{ values[state] if state in values.keys() else 'off' }}
  mode_state_topic: "ebusd/ctlv0/z1OpMode"
  mode_command_template: >-
    {% set values = { 'auto':'auto', 'heat':'day', 'cool':'night', 'off':'off'} %}
    {{ values[value] if value in values.keys() else 'auto' }}
  mode_command_topic: "ebusd/ctlv0/z1OpMode/set"
  current_temperature_topic: "ebusd/ctlv0/z1RoomTemp"
  current_temperature_template: '{{value_json["tempv"].value}}'
  temperature_state_topic: "ebusd/ctlv0/z1ActualRoomTempDesired/set"
  temperature_state_template: '{{value_json["tempv"].value}}'
  temperature_low_state_topic: "ebusd/ctlv0/z1NightTemp"
  temperature_low_state_template: '{{value_json["tempv"].value}}'
  temperature_high_state_topic: "ebusd/ctlv0/z1DayTemp"
  temperature_high_state_template: '{{value_json["tempv"].value}}'
```

![termostato](https://user-images.githubusercontent.com/72525661/208287571-e93c1523-85ea-495b-9882-4c502c08056b.jpg)
  i config that 👍 

homeassistant -> valliant
1 work when on , off , and other mode 
2 temperature room is correct

NO WORK
valliant -. homeassistant  : dont see actual mode on valliant
dont work temperature desiderad

Can suggest me ?

**Comment by pepsonEL** [comment]
Did you found solution ?

**Comment by Koky05** [comment]
It hard to say where is problem because we can not see your mqtt mesages, but in my case is state in different hierarchy:
{% set state = value_json['0']['value'] %}

For temperature desire skip "/set" part, like this (set is only for commands):
temperature_state_topic: "ebusd/ctlv0/z1ActualRoomTempDesired"

My end of config:
```
    mode_command_topic: "ebusd/f47/Hc1OPMode/set"
    value_template: "{{ value_json.temp1.value }}"
    temperature_state_topic: "ebusd/f47/DisplayedHc1RoomTempDesired"
    temperature_low_state_topic: "ebusd/f47/Hc1NightTemp"
    temperature_high_state_topic: "ebusd/f47/Hc1DayTemp"
    temperature_low_command_topic: "ebusd/f47/Hc1NightTemp/set"
    temperature_high_command_topic: "ebusd/f47/Hc1DayTemp/set"
    current_temperature_topic: "ebusd/f47/DisplayedRoomTemp"
    current_temperature_template: "{{ (value_json.temp.value | float(0)) }}"
```

**Comment by pepsonEL** [comment]
Did you resolved your problem ?

**Comment by pepsonEL** [comment]
How i can get status for sensor which has 1 or 0 value ? It looks in mqtt explorer as:
Hc1PumpStatus = { "0": {"name": "", "value": 1}}
get = 1



For thermostat i have this and it works:


  - name: "Parter podłogówka"
    max_temp: 30
    min_temp: 5
    precision: 0.1
    temp_step: 0.5
    modes:
      - "auto"
      - "heat"
      - "cool"
      - "off"
    mode_state_template: >-
      {% set values = { 'auto':'auto', 'day':'heat',  'night':'cool', 'off':'off'} %}
      {% set state = value_json["opmode"].value %}
      {{ values[state] if state in values.keys() else 'off' }}
    mode_state_topic:  "ebusd/700/z2OpMode"
    mode_command_topic: "ebusd/700/z2OpMode/set"
    mode_command_template: >-
      {% set values = { 'auto':'auto', 'heat':'day', 'cool':'night', 'off':'off'} %}
      {{ values[value] if value in values.keys() else 'auto' }}
    temperature_low_state_topic: "ebusd/700/z2NightTemp"
    temperature_low_state_template: '{{value_json["tempv"].value}}'
    temperature_high_state_topic: "ebusd/700/z2DayTemp"
    temperature_high_state_template: '{{value_json["tempv"].value}}'
    temperature_low_command_topic: "ebusd/700/z2NightTemp/set"
    temperature_high_command_topic: "ebusd/700/z2DayTemp/set"
    current_temperature_topic: "ebusd/700/z2RoomTemp"
    current_temperature_template: '{{value_json["tempv"].value}}'

**Comment by arnaudpn** [comment]
Hello,

I just faced the exact same issue.
Current status couldn't be retrieved correctly.
"Problem" lies in the OpMode json (double value)...
ebusd/700/Z1OpMode:
```
{
  "value": {
    "value": "auto"
  }
}
```

==> the value needs to be retrived this way as a consequence:
```
{% set state = value_json["value"].value %}
```

Here is my full configuration which now works like a charm for a VRC700.

/root/config/configuration.yaml
```
mqtt:                                                                                    
  climate:                                                                               
      name: VRC700                                                                       
      max_temp: 23                                                                       
      min_temp: 15                                                                       
      precision: 0.1                                                                     
      temp_step: 0.5                                                                     
                                                                                         
      modes:                                                                             
       - 'auto'                                                                            
       - 'heat'                                                                            
       - 'cool'                                                                         
       - 'off'                                                                           
 
      mode_state_template: >-
        {% set values = { 'auto':'auto', 'day':'heat', 'night':'cool', 'off':'off'} %}
        {% set state = value_json["value"].value %}
        {{ values[state] if state in values.keys() }}
      mode_state_topic: "ebusd/700/Z1OpMode"

      mode_command_template: >-
        {% set values = { 'auto':'auto', 'heat':'day', 'cool':'night', 'off':'off'} %}
        {{ values[value] if value in values.keys() }}
      mode_command_topic: "ebusd/700/Z1OpMode/set"
                                                                          
      temperature_state_topic: "ebusd/700/Z1ActualRoomTempDesired"
      temperature_state_template: "{{ value_json.value.value }}"
      temperature_command_topic: "ebusd/700/Z1ActualRoomTempDesired/set"

      current_temperature_topic: "ebusd/700/Z1RoomTemp"           
      current_temperature_template: "{{ value_json.value.value }}"
```

Result:
<img width="346" height="402" alt="Screenshot 2026-03-22 at 11 30 51" src="https://github.com/user-attachments/assets/bcfe6007-2982-43ec-92ad-c16cdd9f927d" />
