### DISCUSSION TITLE
Docker Compose file - Portainer Stack which works

### DISCUSSION THREAD

**Discussion by martin8310** [john30/ebusd#767] [General]
Because there is no compose file example in the wiki, here is one.

```
version: "3.7"

services:
  ebusd:
    image: john30/ebusd
    container_name: ebusd
    network_mode: host
    devices:
      - "/dev/ttyUSB_eBusd:/dev/ttyUSB0"

    environment:
      - EBUSD_SCANCONFIG=
      - EBUSD_DEVICE=/dev/ttyUSB0
      - EBUSD_PORT=8889
      - EBUSD_MQTTPORT=1883
      - EBUSD_MQTTHOST=192.168.1.3
      - EBUSD_MQTTJSON=
      - EBUSD_MQTTINT=/etc/ebusd/mqtt-hassio.cfg
      - EBUSD_MQTTTOPIC=eBusd/%circuit/%name
      #- EBUSD_CONFIGPATH=/tmp/de/
      - EBUSD_CONFIGLANG=DE
      - EBUSD_ACCESSLEVEL=*

    volumes:
      - /docker_folder/ebusd/tmp:/tmp/
      - /docker_folder/ebusd/etc:/etc/ebusd/
```

**Comment by Koky05** [comment]
Here is my docer-compose config:
```
version: "3.9"

services:
  #eBus Deamon
  ebusd:
    image: john30/ebusd:devel
    container_name: ebusd
    depends_on:
      - mqtt
    #ports: 
    #  - "8888:8888/tcp"
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Bratislava
      - EBUSD_ARCH=amd64
      - EBUSD_SCANCONFIG=full
      - EBUSD_CONFIGPATH=/etc/ebusd/ebusd-configuration/ebusd-2.1.x/en
      - EBUSD_LOGAREAS=all
      - EBUSD_LOGLEVEL=info
      - EBUSD_LATENCY=80000
      - EBUSD_RECEIVETIMEOUT=10000
      - EBUSD_ACQUIRETIMEOUT=20000
      - EBUSD_RECEIVETIMEOUT=80000
      - EBUSD_ACQUIRERETRIES=10
      - EBUSD_SENDRETRIES=10
      - EBUSD_ACCESSLEVEL=*
      - EBUSD_MQTTHOST=192.168.1.7
      - EBUSD_MQTTPORT=1883
      - EBUSD_MQTTUSER=yyyyyyyy
      - EBUSD_MQTTPASS=xxxxxxxxx
      - EBUSD_MQTTTOPIC=ebusd
      - EBUSD_MQTTJSON=
      - EBUSD_MQTTINT=/etc/ebusd/mqtt-hassio.cfg
      - EBUSD_MQTTVERBOSE=
      - EBUSD_MQTTRETAIN=
      - EBUSD_MQTTCHANGES=
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/volume1/docker/ebusd/data:/data"
      - "/volume1/docker/ebusd:/ebusd"
      - "/volume1/docker/ebusd/config:/etc/ebusd"
      - "/volume1/docker/ebusd/log:/var/log"
    command: -d enh:192.168.1.31:9999 -l /var/log/ebusd.log
```
