### DISCUSSION TITLE
z1DayTemp - no reports

### DISCUSSION THREAD

**Discussion by GieBek** [john30/ebusd#821] [General]
Hi, I have had the ebusd module for two days and noticed that the reports are not coming "z(1/2/3)DayTemp"

Vaillant VC 20CS/1-7 (N-PL) ecoTEC exclusive
Vaillant sensoCOMFORT VRC 720
Vaillant sensoNET VR 921

Do I have something set wrong?

![Screenshot_20230128_011547_Home Assistant](https://user-images.githubusercontent.com/9890042/215230658-842b3947-7719-45d6-b67e-1dfdf321d82b.jpg)
![Screenshot_20230128_011629_Home Assistant](https://user-images.githubusercontent.com/9890042/215230684-1c81b03a-ac05-4967-9225-8744ef01ab4c.jpg)

<img width="1273" alt="1" src="https://user-images.githubusercontent.com/9890042/215232029-ad6ea140-838c-4697-a3c7-90aec782c8a2.png">
<img width="904" alt="2" src="https://user-images.githubusercontent.com/9890042/215232033-53fb7544-427a-4bd3-afed-99e1b99aaa1d.png">

**Comment by Dinth** [comment]
I dont have this device, but have you checked if you can see
z1DayTemp/z2DayTemp via ebusctl?

On Sat, 28 Jan 2023 at 00:51, Grzegorz Budzisz ***@***.***>
wrote:

> Hi, I have had the ebusd module for two days and noticed that the reports
> are not coming "z(1/2/3)DayTemp"
>
> Vaillant VC 20CS/1-7 (N-PL) ecoTEC exclusive
> Vaillant sensoCOMFORT VRC 720
> Vaillant sensoNET VR 921
>
> Do I have something set wrong?
>
> [image: Screenshot_20230128_011547_Home Assistant]
> <https://user-images.githubusercontent.com/9890042/215230658-842b3947-7719-45d6-b67e-1dfdf321d82b.jpg>
> [image: Screenshot_20230128_011629_Home Assistant]
> <https://user-images.githubusercontent.com/9890042/215230684-1c81b03a-ac05-4967-9225-8744ef01ab4c.jpg>
>
> [image: 1]
> <https://user-images.githubusercontent.com/9890042/215232029-ad6ea140-838c-4697-a3c7-90aec782c8a2.png>
>
> [image: 2]
> <https://user-images.githubusercontent.com/9890042/215232033-53fb7544-427a-4bd3-afed-99e1b99aaa1d.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/john30/ebusd/discussions/821>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACMSSUC6Y6RJMUZ6N3Y3FDWURUQXANCNFSM6AAAAAAUJKRWHY>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>


-- 
Kind regards,
Michal Gawronski-Kot
***@***.***

**Reply by GieBek** [reply]
Thanks for the answer. Is ebusctl a connection via COM port, if so it doesn't work either :(.

My hands are falling off, I can't get the climate integration to work properly.
Whatever I enter, I can't change the set temperature. If I change the temperature in the application on MyVaillant, the only values that change are:

ebusd/720/z1ActualRoomTempDesired
or
ebusd/720/z1QuickVetoTemp

Depending on whether I have automatic or manual mode.


```
mqtt:
  climate:
    - name: Parter podłogówka
      min_temp: 15
      max_temp: 30
      precision: 0.1
      temp_step: 0.5
      modes:
        - "auto"
        - "heat"
        - "cool"
        - "off"
      mode_state_template: >-
        {% set values = { 'auto':'auto', 'day':'heat', 'night':'cool', 'off':'off'} %}
        {% set state = value_json["opmode"].value %}
        {{ values[state] if state in values.keys() else 'off' }}
      mode_state_topic: "ebusd/720/z1OpMode"
      mode_command_topic: "ebusd/720/z1OpMode/set"
      mode_command_template: >-
        {% set values = { 'auto':'auto', 'heat':'day', 'cool':'night', 'off':'off'} %}
        {{ values[value] if value in values.keys() else 'auto' }}
      temperature_state_topic: "ebusd/720/z1ActualRoomTempDesired"
      temperature_state_template: '{{value_json["tempv"].value}}'
      temperature_command_topic: "ebusd/720/z1ActualRoomTempDesired/set"
      current_temperature_topic: "ebusd/720/z1RoomTemp"
      current_temperature_template: '{{value_json["tempv"].value}}'
```
