### DISCUSSION TITLE
Home Assistant additional control element

### DISCUSSION THREAD

**Discussion by M0nk3yOo** [john30/ebusd#851] [Q&A]
Dear all,

I'm very new with HA and got ebus now working via mqtt. In addition I found out the additional config params for the ebusd service on raspberry to get some controls enabled. But I'm missing some.
May someone tell me how to enable the following settings as like 

<img width="621" alt="image" src="https://user-images.githubusercontent.com/32765291/222926747-4498e404-a7e7-4671-ab58-69a466b5a494.png">

I'll add the following:
- ehp BackupModeHwc
- hwc StorageTempDesiredStart
- hwc StorageTempDesiredStop

Thanks!
André

**Comment by M0nk3yOo** [comment]
I now just using automation to send values via MQTT to ebusd

**Reply by chonghuwa** [reply]
May i ask you how exactly to set this hwc StorageTempDesiredStop ?

**Reply by M0nk3yOo** [reply]
Sure!

I've this in my action (automation) I hope it helps you:

`service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: ebusd/hwc/StorageTempDesiredStop/set
      payload: "{{ states('input_number.helfer_heizungheisswasserendtemperatur') }}"`

Unfortunately the format is lost after saving this post :-(

**Comment by nightmare28** [comment]
hello i got this switched displayed, too. my ebusd is installed inside docker. but after pushing the switch, nothing will be done by the ehp, maybe there is something wrong with my config :-(

**Comment by Koky05** [comment]
You can also create number mqtt sensor in HA by adding next lines into configuraton.yaml:

```
mqtt:
   number:
    - name: StorageTempDesiredStop
      unique_id: hwc_StorageTempDesiredStop
      entity_category: config
      state_topic: 'ebusd/hwc/StorageTempDesiredStop'
      command_topic: 'ebusd/hwc/StorageTempDesiredStop/set'
      payload_available: 'true'
      payload_not_available: 'false'
      qos: 2
      value_template: >
        {{ value_json['temp']['value'] }}
```
