### ISSUE TITLE
Docker-compose problems with env variables

### ISSUE THREAD

**Issue by Dinth** [john30/ebusd#1533]
### Description

Hi. I am trying to migrate from docker standalone container to docker-compose:
Here is my current version of the compose file:
```
version: "3.8"
services:
  ebusd:
    container_name: ebusd
    environment:
      - EBUSD_MQTTINT=/etc/ebusd/mqtt-hassio.cfg
      - EBUSD_MQTTJSON="true"
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - EBUSD_FOREGROUND=
      - EBUSD_MQTTHOST=10.10.1.11
      - EBUSD_MQTTPORT=1883
      - EBUSD_MQTTCLIENTID="ebusd"
      - EBUSD_MQTTUSER="[[MQTT_USERNAME]]"
      - EBUSD_MQTTPASS="[[MQTT_PASSWORD]]"
      - EBUSD_MQTTVAR="filter-direction=r|u|^w"
      - EBUSD_MQTTLOG=""
      - EBUSD_ACCESSLEVEL="*"
      - EBUSD_SCANCONFIG=""
      - EBUSD_DEVICE="ens:/10.10.25.8:9999"
    hostname: ebusd
    image: john30/ebusd:latest
    ipc: private
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ebusd
    ports:
      - 8888:8888/tcp
    restart: unless-stopped
    volumes:
      - /opt/docker/ebusd/ebusd_data:/etc/ebusd
networks:
  ebusd:
    name: ebusd
    driver: bridge
    external: false
volumes:
  ebusd_data:
```

Im getting multiple issues with this:
1. EBUSD_SCANCONFIG doesnt seem to work. Im getting the following 
`ebusd  | 2025-04-21 06:07:00.021 [main notice] invalid/unknown argument in env (ignored): EBUSD_SCANCONFIG=""`
or if i want to specify EBUSD_SCANCONFIG="full", its a very similar message
2. Similar problem with EBUSD_MQTTLOG. Im getting this:
```
ebusd  | 2025-04-21 06:09:13.822 [main error] invalid argument in env: EBUSD_MQTTLOG=""
ebusd  | 2025-04-21 06:09:13.822 [main error] invalid arguments
```
I have also tried setting this to "true", but same problem.
3. Most important one is with the device though. Before i've been using "-d ens:10.10.25.8:9999" and ebus was working with that.
Now, if i want to use EBUSD_DEVICE="ens:10.10.25.8:9999" i get the following error:
`2025-04-21 06:15:06.646 [main error] unable to create protocol/device "ens:10.10.25.8:9999"`

and when i adjust EBUSD_DEVICE="ens:/10.10.25.8:9999" i get the following:

```
2025-04-21 06:13:53.970 [bus error] unable to open "ens:/10.10.25.8:9999": ERR: element not found
2025-04-21 06:13:53.971 [main notice] ebusd 25.1.25.1 started with broadcast scan on device: "ens:/10.10.25.8:9999", serial
2025-04-21 06:13:54.488 [bus notice] bus started with own address 31/36
2025-04-21 06:13:54.488 [bus notice] device invalid
2025-04-21 06:13:54.781 [mqtt error] connection refused: 5
2025-04-21 06:13:54.781 [mqtt error] communication error: connection refused
2025-04-21 06:13:59.489 [bus error] unable to open "ens:/10.10.25.8:9999": ERR: element not found
2025-04-21 06:13:59.489 [bus notice] device invalid
```

### Actual behavior

I cannot make the ebusd stack to run 

### Expected behavior

All those env variables should work as per docker-compose example on github

### ebusd version

25.1

### ebusd arguments

N/A

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

x64

### Dockerized

latest

### Hardware interface

Adapter v3 Ethernet

### Logs

Logs pasted above
