### ISSUE TITLE
v22.1: Mqtt messages format changed and requires additional parsing

### ISSUE THREAD

**Issue by andig** [john30/ebusd#535]
### Description

Follow-up to https://github.com/john30/ebusd/issues/524, same config.

After upgrading to Docker `latest`, I still don't see data in my monitoring:

<img width="1141" alt="Screenshot 2022-02-16 at 08 26 20" src="https://user-images.githubusercontent.com/184815/154216259-3835f570-99e3-42d6-8205-c6aeb8c44ae2.png">

Looking into the topics it seems as if the message format has changed:

<img width="595" alt="Screenshot 2022-02-16 at 08 22 30" src="https://user-images.githubusercontent.com/184815/154216116-a463292a-aa6b-405d-99fa-564926e8ecc6.png">

Note that the messages are no longer simple (and immediately-usable) numeric value but concatenated strings. Is this intentional?

Going back to v21.3 confirms that the "simple" message format behaviour is restored.

**Comment by john30** [comment]
seems you forgot to use "--mqttjson"

**Comment by andig** [comment]
I've always run it like this:

```
  ebusd:
    container_name: ebusd
    image: john30/ebusd:v21.3
    ports:
      - 8888:8888
    command: --enabledefine --enablehex --accesslevel='*' --scanconfig -f -d
      192.168.0.46:9999 --latency 20000 --mqtthost=nas.fritz.box --mqttport=1883
    restart: always
```

I do not want to have json- which I need to parse- but just the plain numeric values for those topics that support it. That has been the behaviour sofar. Consider

    bai;FlowTempDesired;36.00

instead I expect

    36.00

like it used to be.
